### PR TITLE
12292 - Implemented code for  FSS Tooling Tidy UI - AB#12292

### PR DESCRIPTION
**Pull request by Ashish15251**
12292 - Implemented code for  FSS Tooling Tidy UI - AB#12292

### CODE REVIEW

**Review by crdandoukho — APPROVED** [review]
LGTM!

Time permitting, I think it would be a good idea to show and tell this to Jacqui before it's merged into main

**Review by bhalcha13813 — APPROVED** [review]
LGTM

**Review by crdandoukho — APPROVED** [review]
LGTM

**Review by barrie-cooper — APPROVED** [review]
LGTM

**Pull request merged**
